repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: bash -c "scripts/isort.sh --format"
      language: system
      types: [python]
      pass_filenames: false
    - id: black
      name: black
      entry: bash -c "scripts/black.sh --format"
      language: system
      types: [python]
      pass_filenames: false
    - id: flake8
      name: flake8
      entry: bash -c "scripts/flake8.sh"
      language: system
      types: [python]
      pass_filenames: false
